"""Message type definitions for socket protocol."""
from enum import Enum


class MessageType(str, Enum):
    """All message types used in the socket protocol."""
    
    # Authentication
    SIGNUP = "SIGNUP"
    SIGNUP_RESPONSE = "SIGNUP_RESPONSE"
    LOGIN = "LOGIN"
    LOGIN_RESPONSE = "LOGIN_RESPONSE"
    LOGOUT = "LOGOUT"
    LOGOUT_RESPONSE = "LOGOUT_RESPONSE"
    
    # Room Management
    CREATE_ROOM = "CREATE_ROOM"
    CREATE_ROOM_RESPONSE = "CREATE_ROOM_RESPONSE"
    ADD_MEMBER = "ADD_MEMBER"
    ADD_MEMBER_RESPONSE = "ADD_MEMBER_RESPONSE"
    REMOVE_MEMBER = "REMOVE_MEMBER"
    REMOVE_MEMBER_RESPONSE = "REMOVE_MEMBER_RESPONSE"
    SET_ROLE = "SET_ROLE"
    SET_ROLE_RESPONSE = "SET_ROLE_RESPONSE"
    LIST_ROOMS = "LIST_ROOMS"
    LIST_ROOMS_RESPONSE = "LIST_ROOMS_RESPONSE"
    LIST_MEMBERS = "LIST_MEMBERS"
    LIST_MEMBERS_RESPONSE = "LIST_MEMBERS_RESPONSE"
    
    # File Operations
    LIST_FILES = "LIST_FILES"
    LIST_FILES_RESPONSE = "LIST_FILES_RESPONSE"
    FILE_DETAIL = "FILE_DETAIL"
    FILE_DETAIL_RESPONSE = "FILE_DETAIL_RESPONSE"
    FILE_VERSIONS = "FILE_VERSIONS"
    FILE_VERSIONS_RESPONSE = "FILE_VERSIONS_RESPONSE"
    DELETE_FILE = "DELETE_FILE"
    DELETE_FILE_RESPONSE = "DELETE_FILE_RESPONSE"
    
    # Upload
    INIT_UPLOAD = "INIT_UPLOAD"
    UPLOAD_PLAN = "UPLOAD_PLAN"
    
    # Download
    INIT_DOWNLOAD = "INIT_DOWNLOAD"
    DOWNLOAD_PLAN = "DOWNLOAD_PLAN"
    
    # Share Tokens
    CREATE_SHARE_TOKEN = "CREATE_SHARE_TOKEN"
    CREATE_SHARE_TOKEN_RESPONSE = "CREATE_SHARE_TOKEN_RESPONSE"
    
    # Notifications
    SUBSCRIBE_ROOM = "SUBSCRIBE_ROOM"
    SUBSCRIBE_ROOM_RESPONSE = "SUBSCRIBE_ROOM_RESPONSE"
    UNSUBSCRIBE_ROOM = "UNSUBSCRIBE_ROOM"
    UNSUBSCRIBE_ROOM_RESPONSE = "UNSUBSCRIBE_ROOM_RESPONSE"
    EVENT = "EVENT"
    
    # Storage Node Communication
    STORAGE_AUTH = "STORAGE_AUTH"
    STORAGE_AUTH_RESPONSE = "STORAGE_AUTH_RESPONSE"
    PING = "PING"
    PONG = "PONG"
    VERIFY_TICKET = "VERIFY_TICKET"
    TICKET_VALID = "TICKET_VALID"
    TICKET_INVALID = "TICKET_INVALID"
    UPLOAD_COMPLETE = "UPLOAD_COMPLETE"
    UPLOAD_FAILED = "UPLOAD_FAILED"
    ACK = "ACK"
    
    # Health Check
    STATUS = "STATUS"
    STATUS_RESPONSE = "STATUS_RESPONSE"
    
    # Error
    ERROR = "ERROR"
